---
- name: Execute {{ va }} VA stages
  block:
    - ansible.builtin.debug:
        var: item

    - ansible.builtin.set_fact:
        stage_path: "{{ item['path'] }}"

    - name: Handle values generation
      ansible.builtin.include_tasks: values.yaml
      loop: "{{ item['values'] }}"

    - name: Build CRs
      ansible.builtin.shell: kustomize build
      args:
        chdir: "{{ base_path }}/va_repo/{{ item['path'] }}"
      register: kustomize_built_crs

    - name: Write-out CRs
      ansible.builtin.copy:
        content: "{{ kustomize_built_crs.stdout }}"
        dest: "{{ base_path }}/va_repo/{{ item['path'] }}/staged_crs.yaml"

    - name: Apply CRs
      ansible.builtin.debug:
        msg: "oc apply -f {{ base_path }}/va_repo/{{ item['path'] }}/staged_crs.yaml"
      # ansible.builtin.shell: "oc apply -k {{ base_path }}/va_repo/{{ item['path'] }}"

    - name: Wait for stage to finish
      ansible.builtin.debug:
        msg: "{{ cmd }}"
      # ansible.builtin.shell: "{{ cmd }}"
      loop_control:
        loop_var: cmd
      loop: "{{ item['validations'] }}"
