---
base_path: /home/ocp
vas:
  hci:
    repo: https://github.com/abays/architecture.git
    branch: va1_edpm_kustomize_2
    stages:
    - path: examples/va/hci/control-plane/nncp
      validation: "oc wait nncp --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured --timeout=60" 
      values:
      - name: network-values
        src_file: network_values.yaml
        dest_file: values.yaml

    - path: examples/va/hci/control-plane
      validation: "oc wait osctlplane controlplane --for condition=Ready --timeout=600s"
      values:
      - name: network-values
        src_file: network_values.yaml
        dest_file: nncp/values.yaml

    - path: examples/va/hci/edpm-pre-ceph
      validation: "oc wait osdpd edpm-deployment-pre-ceph --for condition=Ready --timeout=1200s"
      values:
      - name: edpm-values
        src_file: edpm_pre_ceph_values.yaml
        dest_file: values.yaml

    - path: examples/va/hci
      validation: "oc wait osdpd edpm-deployment-post-ceph --for condition=Ready --timeout=1200s"
      values:
      - name: service-values
        src_file: edpm_post_ceph_service_values.yaml
        dest_file: service-values.yaml
      - name: edpm-values-post-ceph
        src_file: edpm_post_ceph_edpm_values.yaml
        dest_file: values.yaml
